# Generated by Django 4.1.3 on 2023-09-21 14:01

from django.db import migrations, models
import tool.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.TextField(blank=True, max_length=255, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("1", "single"), ("2", "group")], max_length=10
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="chat/avatar"),
                ),
                ("last_action", models.DateTimeField(blank=True, null=True)),
                ("last_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Chat",
                "db_table": "tb_chat",
                "ordering": ["-last_action"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("context", models.TextField(blank=True, null=True)),
                (
                    "media",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=tool.models.message_file_upload_path,
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Message",
                "db_table": "tb_message",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="Noti",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("1", "like_video"),
                            ("2", "comment_video"),
                            ("3", "like_comment"),
                            ("4", "comment_comment"),
                            ("5", "follow"),
                        ],
                        max_length=10,
                    ),
                ),
                ("context", models.TextField()),
                ("status", models.BooleanField(default=False)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Notification",
                "db_table": "tb_noti",
                "ordering": ["-create_time"],
            },
        ),
        migrations.CreateModel(
            name="SearchRecent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Search recent",
                "db_table": "tb_search_recent",
                "ordering": ["-create_time"],
            },
        ),
    ]
