# Generated by Django 4.1.3 on 2023-09-03 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchrecent',
            options={'ordering': ['-create_time'], 'verbose_name': 'Search recent'},
        ),
        migrations.AddField(
            model_name='searchrecent',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
