# Generated by Django 4.1.3 on 2023-10-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noti',
            name='user_interact',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='noti',
            name='context',
            field=models.CharField(max_length=255),
        ),
    ]
