# Generated by Django 4.1.3 on 2023-10-08 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_music_name'),
        ('tool', '0003_noti_user_interact_alter_noti_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noti',
            name='video',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_noti', to='video.video'),
        ),
    ]
