# Generated by Django 4.1.3 on 2023-09-04 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_noti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noti',
        ),
    ]
