# Generated by Django 4.1.7 on 2023-09-11 02:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("tool", "0005_noti"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noti",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
