# Generated by Django 4.2.5 on 2023-10-10 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tool", "0005_noti_user_send"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["create_time"], "verbose_name": "Message"},
        ),
    ]
