# Generated by Django 4.1.3 on 2023-10-13 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-create_time'], 'verbose_name': 'Message'},
        ),
    ]
