# Generated by Django 4.1.3 on 2023-09-11 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_group_singlechat_groupchat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupchat',
            old_name='image',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='singlechat',
            old_name='image',
            new_name='media',
        ),
    ]
