# Generated by Django 4.2.5 on 2023-11-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tool", "0008_setup"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="name_partner",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
