# Generated by Django 4.1.3 on 2023-09-11 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tool.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tool', '0008_rename_image_groupchat_media_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(max_length=255)),
                ('type', models.CharField(choices=[('1', 'single'), ('2', 'group')], max_length=10)),
                ('avatar', models.ImageField(upload_to='media/chat/avatar')),
                ('last_action', models.DateTimeField()),
                ('last_message', models.TextField(blank=True, null=True)),
                ('member', models.ManyToManyField(blank=True, related_name='chat_member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat',
                'db_table': 'tb_chat',
                'ordering': ['-last_action'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField(blank=True, null=True)),
                ('media', models.FileField(blank=True, null=True, upload_to=tool.models.message_file_upload_path)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('reader', models.ManyToManyField(blank=True, related_name='reader', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='tool.chat')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'db_table': 'tb_message',
                'ordering': ['-create_time'],
            },
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='reader',
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='singlechat',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='singlechat',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupChat',
        ),
        migrations.DeleteModel(
            name='SingleChat',
        ),
    ]
