# Generated by Django 4.1.3 on 2023-09-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0009_chat_message_remove_groupchat_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(upload_to='chat/avatar'),
        ),
    ]
