# Generated by Django 4.1.3 on 2023-09-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0010_alter_chat_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='chat/avatar'),
        ),
        migrations.AlterField(
            model_name='chat',
            name='last_action',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
