# Generated by Django 4.2.5 on 2023-11-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tool", "0010_remove_chat_name_partner"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="partner",
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
