# Generated by Django 4.1.7 on 2023-08-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_username_logauthen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
