# Generated by Django 4.1.7 on 2023-08-30 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_userstatus_delete_logauthen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstatus",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_status",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
