# Generated by Django 4.1.7 on 2023-08-30 08:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="music",
            field=models.FileField(
                upload_to="music",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp3"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(
                upload_to="video",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4"]
                    )
                ],
            ),
        ),
    ]
