# Generated by Django 4.1.7 on 2023-08-30 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0002_alter_music_music_alter_video_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="likecomment",
            name="like",
        ),
        migrations.RemoveField(
            model_name="likevideo",
            name="like",
        ),
    ]
