# Generated by Django 4.1.7 on 2023-08-30 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0003_remove_likecomment_like_remove_likevideo_like"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="save",
            name="save",
        ),
    ]
