# Generated by Django 4.1.7 on 2023-08-30 10:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0004_remove_save_save"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
