# Generated by Django 4.1.7 on 2023-08-31 04:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0005_alter_music_id_alter_video_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="music",
            name="descrip",
        ),
        migrations.RemoveField(
            model_name="music",
            name="name",
        ),
    ]
