# Generated by Django 4.1.7 on 2023-08-31 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0006_remove_music_descrip_remove_music_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="music",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_music",
                to="video.music",
            ),
        ),
    ]
